(function(){
'use strict';
const E=window.OzonElasticity, X=window.OzonXlsx;
const $=id=>document.getElementById(id);
const state={campaigns:new Map(),files:[],sourceOrder:0,analysis:[],selected:null,sortKey:'confidence',sortDir:-1};
const fmt0=n=>Number.isFinite(n)?Math.round(n).toLocaleString('ru-RU'):'—';
const fmt1=n=>Number.isFinite(n)?n.toLocaleString('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1}):'—';
const fmt2=n=>Number.isFinite(n)?n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const money=n=>Number.isFinite(n)?Math.round(n).toLocaleString('ru-RU')+' ₽':'—';
const pct=n=>Number.isFinite(n)?(n*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+'%':'—';
const eFmt=n=>Number.isFinite(n)?(n>0?'+':'')+n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const isoToday=()=>{const d=new Date();const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`};
const ruDate=iso=>iso?iso.split('-').reverse().join('.'):'—';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function setStatus(msg,kind='muted'){$('status').className='status '+kind;$('status').textContent=msg;}
function currentCampaignRows(){const id=$('campaignSelect').value;const m=state.campaigns.get(id);return m?[...m.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.sku.localeCompare(b.sku)):[];}
function mergeRows(rows){for(const r of rows){if(!state.campaigns.has(r.campaignId))state.campaigns.set(r.campaignId,new Map());const m=state.campaigns.get(r.campaignId);const key=r.date+'|'+r.sku;const old=m.get(key);if(!old||r.sourceOrder>=old.sourceOrder)m.set(key,r);}}
async function ingestFiles(files){
  if(!files.length)return;setStatus('Читаю XLSX…');
  for(const file of files){
    try{const ab=await file.arrayBuffer();const parsed=await X.readOzonWorkbook(ab);state.sourceOrder++;const rows=E.normalizeOzonRows(parsed.rows,parsed.campaignId,state.sourceOrder);mergeRows(rows);state.files.push({name:file.name,campaignId:parsed.campaignId,rows:rows.length});}
    catch(err){setStatus(`Ошибка ${file.name}: ${err.message}`,'error');return;}
  }
  renderFiles();refreshCampaignSelect();setStatus(`Загружено файлов: ${state.files.length}. Более свежий срез заменяет старые данные того же РК / SKU / дня.`,'ok');
}
function renderFiles(){$('fileList').innerHTML=state.files.map(f=>`<span class="file-chip">${esc(f.name)} · РК ${esc(f.campaignId)} · ${f.rows} строк</span>`).join('');}
function refreshCampaignSelect(){const sel=$('campaignSelect'),old=sel.value;sel.innerHTML=[...state.campaigns.keys()].sort().map(id=>`<option value="${id}">РК ${id}</option>`).join('');if(old&&state.campaigns.has(old))sel.value=old;autoRange();}
function autoRange(){const rows=currentCampaignRows();if(!rows.length)return;const r=E.suggestRollingRange(rows,isoToday(),21);if(!r)return;$('analysisStart').value=r.startDate;$('analysisEnd').value=r.endDate;$('windowNote').innerHTML=(r.lastDayExcluded?`Текущий день <strong>${ruDate(isoToday())}</strong> автоматически исключён. `:'')+`Рекомендации строятся по выбранному актуальному окну; <strong>идентифицируемость E использует всю загруженную историю</strong>.`;analyze();}
function getSettings(){const maxCpo=Number($('maxIncCpo').value);return {startDate:$('analysisStart').value,endDate:$('analysisEnd').value,minCpcChange:(Number($('minCpcChange').value)||5)/100,bootstrapIterations:Number($('bootstrapIterations').value)||400,maxIncrementalCpo:maxCpo>0?maxCpo:null,todayIso:isoToday()};}
function campaignDailyInRange(rows,s){return E.campaignDaily(rows).filter(d=>d.date>=s.startDate&&d.date<=s.endDate&&d.date!==s.todayIso);}
function analyze(){const rows=currentCampaignRows();if(!rows.length)return;const s=getSettings();if(!s.startDate||!s.endDate||s.startDate>s.endDate)return;state.analysis=E.analyzeCampaignRolling(rows,s);renderKpis(rows,s);renderResults();if(state.selected){const found=state.analysis.find(x=>x.sku===state.selected);if(found)renderDetail(found);}}
function renderKpis(rows,s){
  const daily=campaignDailyInRange(rows,s),last=daily.at(-1),cpcs=daily.map(d=>d.cpc).filter(Number.isFinite);
  $('kpiSku').textContent=state.analysis.length;$('kpiPairs').textContent=fmt0(state.analysis.reduce((sum,x)=>sum+x.informativePairs,0));$('kpiRaise').textContent=state.analysis.filter(x=>x.recommendation.code==='RAISE').length;$('kpiLower').textContent=state.analysis.filter(x=>['LOWER','TRAFFIC_TRAP'].includes(x.recommendation.code)).length;$('kpiTest').textContent=state.analysis.filter(x=>x.experiment?.needed).length;
  $('kpiCpc').textContent=last&&Number.isFinite(last.cpc)?fmt2(last.cpc)+' ₽':'—';$('kpiCpcRange').textContent=cpcs.length?`диапазон ${fmt2(Math.min(...cpcs))}–${fmt2(Math.max(...cpcs))} ₽`:'нет данных';
}
function sortValue(x,key){switch(key){case'sku':return x.sku;case'cpc':return x.currentCpc??-Infinity;case'eClick':return x.eClick??-Infinity;case'eCart':return x.eCart??-Infinity;case'eOrder':return x.eOrder??-Infinity;case'adjustedEOrder':return x.adjustedEOrder??-Infinity;case'pairs':return x.informativePairs;case'marginalCpo':return x.marginalCpo??Infinity;case'confidence':return x.confidence.score;case'identifiability':return x.identifiability?.score??-Infinity;case'recommendation':return x.recommendation.code;case'targetCpc':return x.targetCpc??-Infinity;default:return 0;}}
function filteredAnalysis(){const rf=$('recommendationFilter').value,mf=$('measurementFilter').value,min=Number($('minConfidence').value)||0;let a=state.analysis.filter(x=>(rf==='ALL'||x.recommendation.code===rf)&&(mf==='ALL'||x.identifiability?.code===mf)&&x.confidence.score>=min);return a.sort((x,y)=>{const av=sortValue(x,state.sortKey),bv=sortValue(y,state.sortKey);if(typeof av==='string')return state.sortDir*av.localeCompare(bv);return state.sortDir*((av>bv)-(av<bv));});}
function eClass(n){return !Number.isFinite(n)?'':n>0.15?'e-pos':n<-0.15?'e-neg':'';}
function ciText(ci){return ci&&Number.isFinite(ci.low)&&Number.isFinite(ci.high)?`90%: ${eFmt(ci.low)} … ${eFmt(ci.high)}`:'90%: —';}
function rowHtml(x){const step=x.recommendation.stepPct,exp=x.experiment||{},id=x.identifiability||{},hist=x.history||{},goal=exp.needed?`тест ${fmt2(exp.targetCpc)} ₽`:`${fmt2(x.currentCpc)} → ${fmt2(x.targetCpc)} ₽`,goalSub=exp.needed?`${exp.direction==='RAISE'?'+':'−'}${Math.round(Math.abs(exp.stepPct)*100)}% · ${exp.daysLabel} дн.`:(step?`${step>0?'+':''}${Math.round(step*100)}%`:'без изменения');return `<tr class="result-row" data-sku="${esc(x.sku)}">
<td class="sku-cell"><small class="product-name" title="${esc(x.name)}">${esc(x.name)}</small><span class="product-article">Арт. ${esc(x.sku)}</span></td>
<td><div class="metric-main">${fmt2(x.minCpc)}–${fmt2(x.maxCpc)} ₽</div><div class="metric-sub">текущий ${fmt2(x.currentCpc)} ₽</div></td>
<td><div class="metric-main ${eClass(x.eClick)}">${eFmt(x.eClick)}</div><div class="metric-sub">${ciText(x.ciClick)}</div></td>
<td><div class="metric-main ${eClass(x.eCart)}">${eFmt(x.eCart)}</div><div class="metric-sub">${ciText(x.ciCart)}</div></td>
<td><div class="metric-main ${eClass(x.eOrder)}">${eFmt(x.eOrder)}</div><div class="metric-sub">${ciText(x.ciOrder)}</div></td>
<td><div class="metric-main ${eClass(x.adjustedEOrder)}">${eFmt(x.adjustedEOrder)}</div><div class="metric-sub">p=${Number.isFinite(x.orderPValue)?x.orderPValue.toFixed(3):'—'}</div></td>
<td><div class="metric-main">${x.informativePairs} / ${hist.informativePairs??0}</div><div class="metric-sub">окно / история · эфф. ${fmt1(hist.effectivePairs)}</div></td>
<td><div class="metric-main">${Number.isFinite(x.marginalCpo)?money(x.marginalCpo):'—'}</div><div class="metric-sub">${Number.isFinite(x.marginalRoas)?'mROAS '+fmt1(x.marginalRoas)+'×':'—'}</div></td>
<td><div class="metric-main">режим ${x.regimeKnowledge?.score??'—'} · E ${id.score??'—'}</div><div class="metric-sub">${esc(x.regimeKnowledge?.label||'—')} / ${esc(id.labelScore||'—')}</div></td>
<td><span class="badge ${x.recommendation.code}">${esc(x.recommendation.label)}</span><div class="metric-sub"><span class="measure-badge ${esc(id.code||'')}">${esc(id.label||'—')}</span></div><div class="metric-sub" title="${esc(id.reason||x.recommendation.reason)}">${esc(id.reason||x.recommendation.reason)}</div></td>
<td><div class="metric-main">${goal}</div><div class="step ${exp.needed?(exp.direction==='RAISE'?'up':'down'):(step>0?'up':step<0?'down':'')}">${goalSub}</div></td></tr>`;}
function renderResults(){const a=filteredAnalysis();$('resultsBody').innerHTML=a.length?a.map(rowHtml).join(''):'<tr><td colspan="11" class="empty-cell">Нет SKU под выбранные фильтры.</td></tr>';$('resultsBody').querySelectorAll('tr[data-sku]').forEach(tr=>tr.addEventListener('click',()=>{state.selected=tr.dataset.sku;const x=state.analysis.find(v=>v.sku===state.selected);if(x)renderDetail(x);}));}
function stat(label,value,sub=''){return `<div class="stat-box"><span>${label}</span><strong>${value}</strong>${sub?`<small class="metric-sub">${sub}</small>`:''}</div>`;}
function renderDetail(x){$('detailEmpty').hidden=true;$('detailContent').hidden=false;$('detailTitle').textContent='SKU '+x.sku;$('detailName').textContent=x.name;const exp=x.experiment||{},id=x.identifiability||{},hist=x.history||{};$('detailDecision').innerHTML=`<span class="badge ${x.recommendation.code}">${esc(x.recommendation.label)}</span> <span class="measure-badge ${esc(id.code||'')}">${esc(id.label||'—')}</span>`;
  $('detailStats').innerHTML=stat('E кликов',eFmt(x.eClick),ciText(x.ciClick))+stat('E корзин',eFmt(x.eCart),ciText(x.ciCart))+stat('E заказов',eFmt(x.eOrder),ciText(x.ciOrder))+stat('E заказов adj.',eFmt(x.adjustedEOrder),`p=${Number.isFinite(x.orderPValue)?x.orderPValue.toFixed(3):'—'} · ${x.orderTest?.level||'—'}`)+stat('Текущий режим',`${x.regimeKnowledge?.score??'—'}/100`,x.regimeKnowledge?.label||'—')+stat('Идентифицируемость E',`${id.score??'—'}/100`,id.label||'—')+stat('Точки E',`${fmt0(x.informativePairs)} / ${fmt0(hist.informativePairs)}`,'актуальное окно / вся история')+stat('Эффективные точки',fmt1(hist.effectivePairs),`из ${fmt0(hist.informativePairs)} исторических`)+stat('CPC-зоны',fmt0(hist.distinctBands),`ниже ${fmt0(hist.belowCount)} · выше ${fmt0(hist.aboveCount)}`)+stat('CPC × расход',Number.isFinite(hist.spendCorrelation)?fmt2(hist.spendCorrelation):'—','|corr| близко к 1 = confounding')+stat('Покрытие заказов',pct(x.orderCoverage))+stat('Marginal CPO',Number.isFinite(x.marginalCpo)?money(x.marginalCpo):'—')+stat('CPC диапазон истории',`${fmt2(hist.minCpc)}–${fmt2(hist.maxCpc)} ₽`)+stat('История',hist.historyStart&&hist.historyEnd?`${ruDate(hist.historyStart)}–${ruDate(hist.historyEnd)}`:'—',`${fmt0(hist.completeDays)} полных дней`);
  $('experimentPanel').innerHTML=exp.needed?`<div class="experiment-box"><strong>Чтобы измерить эластичность точнее: ${esc(id.label)}</strong><div>${esc(exp.reason)}</div><div class="experiment-grid"><div><span>Текущий CPC</span><b>${fmt2(x.currentCpc)} ₽</b></div><div><span>Целевой факт. CPC</span><b>${fmt2(exp.targetCpc)} ₽ (${exp.stepPct>0?'+':''}${Math.round(exp.stepPct*100)}%)</b></div><div><span>Минимум полных дней</span><b>${esc(exp.daysLabel)}</b></div><div><span>Цель по событиям</span><b>${exp.volumeTargets.clicks} кликов · ${exp.volumeTargets.carts} корзин · ${exp.volumeTargets.orders} заказов</b></div></div><div class="metric-sub" style="margin-top:9px">${esc(exp.note)} Условия: ${esc(exp.conditions.join('; '))}.</div></div>`:`<div class="experiment-box"><strong>Дополнительный CPC-тест сейчас не обязателен</strong><div>${esc(id.reason||'Эластичность уже достаточно измерена для текущего решения.')}</div></div>`;
  $('chartWrap').innerHTML=miniChart(x.days);$('pairBody').innerHTML=x.pairs.length?x.pairs.map(pairHtml).join(''):'<tr><td colspan="7" class="empty-cell">Нет соседних дней с достаточно сильным изменением CPC.</td></tr>';$('dailyBody').innerHTML=x.days.map(r=>`<tr><td>${ruDate(r.date)}</td><td>${money(E.actualCpc(r))}</td><td>${fmt0(r.clicks)}</td><td>${fmt0(r.carts)}</td><td>${Number.isFinite(r.orderUnitsEstimate)?fmt1(r.orderUnitsEstimate):'—'}</td><td>${r.orderReliable?'<span class="good-text">надёжно</span>':'<span class="warn-text">оценка</span>'}${Number.isFinite(r.orderResidual)?` · ${(r.orderResidual*100).toFixed(1)}%`:''}</td><td>${money(r.spend)}</td><td>${money(r.totalRevenue)}</td></tr>`).join('');
  $('detailPanel').scrollIntoView({behavior:'smooth',block:'start'});
}
function pairHtml(p){return `<tr><td>${ruDate(p.fromDate).slice(0,5)} → ${ruDate(p.toDate).slice(0,5)}</td><td class="${p.cpcArc>0?'e-pos':'e-neg'}">${p.cpcArc>0?'+':''}${pct(p.cpcArc)}</td><td>${p.spendArc>=0?'+':''}${pct(p.spendArc)}</td><td class="${eClass(p.eClick)}">${eFmt(p.eClick)}</td><td class="${eClass(p.eCart)}">${eFmt(p.eCart)}</td><td class="${eClass(p.eOrder)}">${eFmt(p.eOrder)}</td><td>${fmt2(p.weight)}<div class="metric-sub">spend ${fmt2(p.spendWeight)}</div></td></tr>`;}
function miniChart(rows){const data=rows.slice().sort((a,b)=>a.date.localeCompare(b.date));if(!data.length)return'';const W=980,H=380,left=86,right=20,top=18,band=82;const xs=data.map((_,i)=>left+(W-left-right)*(data.length===1?.5:i/(data.length-1)));const metrics=[['CPC',r=>E.actualCpc(r)],['Клики',r=>r.clicks],['Корзины',r=>r.carts],['Общие заказы',r=>r.orderUnitsEstimate]];let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Дневная динамика SKU">`;
  metrics.forEach((m,mi)=>{const vals=data.map(m[1]).map(v=>Number.isFinite(v)?v:null),finiteVals=vals.filter(Number.isFinite);let mn=finiteVals.length?Math.min(...finiteVals):0,mx=finiteVals.length?Math.max(...finiteVals):1;if(mx===mn)mx=mn+1;const y0=top+mi*band,y=v=>y0+58-(v-mn)/(mx-mn)*48;svg+=`<text x="8" y="${y0+17}" class="svg-label">${m[0]}</text><line x1="${left}" y1="${y0+62}" x2="${W-right}" y2="${y0+62}" class="svg-grid"/>`;const pts=[];vals.forEach((v,i)=>{if(Number.isFinite(v))pts.push(`${xs[i].toFixed(1)},${y(v).toFixed(1)}`)});svg+=`<polyline points="${pts.join(' ')}" class="svg-line m${mi}" fill="none"/><text x="${W-right}" y="${y0+17}" text-anchor="end" class="svg-range">${fmt1(mn)}–${fmt1(mx)}</text>`;});data.forEach((r,i)=>{if(i===0||i===data.length-1||i%Math.max(1,Math.floor(data.length/7))===0)svg+=`<text x="${xs[i]}" y="${H-5}" text-anchor="middle" class="svg-date">${ruDate(r.date).slice(0,5)}</text>`;});svg+=`<style>.svg-label{font:700 11px system-ui;fill:#536079}.svg-range,.svg-date{font:10px system-ui;fill:#7b8494}.svg-grid{stroke:#e4e8ef;stroke-width:1}.svg-line{stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round}.m0{stroke:#3157d5}.m1{stroke:#13795b}.m2{stroke:#a36a00}.m3{stroke:#9237a8}</style></svg>`;return svg;}
function exportCsv(){const a=filteredAnalysis();if(!a.length)return;const head=['SKU','Название','CPC min','CPC max','CPC current','Target CPC','E click','E cart','E order','E order adjusted','p order','CI90 E order low','CI90 E order high','Pairs current','Pairs history','Effective pairs history','Regime score','Identifiability score','Measurement status','Spend correlation','CPC bands','Below current','Above current','Experiment target CPC','Experiment days','Marginal CPO','Recommendation','Evidence','CPC step'];const rows=a.map(x=>[x.sku,x.name,x.minCpc,x.maxCpc,x.currentCpc,x.targetCpc,x.eClick,x.eCart,x.eOrder,x.adjustedEOrder,x.orderPValue,x.ciOrder.low,x.ciOrder.high,x.informativePairs,x.history?.informativePairs,x.history?.effectivePairs,x.regimeKnowledge?.score,x.identifiability?.score,x.identifiability?.label,x.history?.spendCorrelation,x.history?.distinctBands,x.history?.belowCount,x.history?.aboveCount,x.experiment?.targetCpc,x.experiment?.daysLabel,x.marginalCpo,x.recommendation.label,x.recommendation.evidence,x.recommendation.stepPct]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=url;ael.download=`ozon_rolling_cpc_elasticity_${$('campaignSelect').value}.csv`;ael.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function bind(){const dz=$('dropzone'),fi=$('fileInput');dz.addEventListener('click',()=>fi.click());dz.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fi.click();}});fi.addEventListener('change',()=>ingestFiles([...fi.files]));['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>ingestFiles([...e.dataTransfer.files].filter(f=>f.name.toLowerCase().endsWith('.xlsx'))));$('campaignSelect').addEventListener('change',autoRange);$('last21').addEventListener('click',autoRange);['analysisStart','analysisEnd','minCpcChange','maxIncCpo','bootstrapIterations'].forEach(id=>$(id).addEventListener('change',analyze));['recommendationFilter','measurementFilter','minConfidence'].forEach(id=>$(id).addEventListener('change',renderResults));$('exportCsv').addEventListener('click',exportCsv);document.querySelectorAll('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{const k=th.dataset.sort;if(state.sortKey===k)state.sortDir*=-1;else{state.sortKey=k;state.sortDir=k==='sku'?1:-1}renderResults();}));}
if(!E||!X){setStatus('Ошибка сборки: не загружено математическое ядро или XLSX-ридер.','error');return;}bind();
})();
