(function(root,factory){
  if(typeof module==='object'&&module.exports) module.exports=factory(require('./price_model.js'));
  else root.OzonElasticity=factory(root.OzonElasticity);
})(typeof globalThis!=='undefined'?globalThis:this,function(E){
'use strict';
if(!E) throw new Error('price_model.js must be loaded before decision_model.js');
const baseAnalyze=E.analyzeCampaignRolling;
let lastDecisionAnalysis=[];
const finite=x=>Number.isFinite(Number(x));
const num=(x,f=0)=>finite(x)?Number(x):f;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const mean=a=>{const v=(a||[]).filter(Number.isFinite);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};
const median=a=>{const v=(a||[]).filter(Number.isFinite).slice().sort((a,b)=>a-b);if(!v.length)return null;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2};
function daysBetween(a,b){const x=Date.parse(a+'T00:00:00Z'),y=Date.parse(b+'T00:00:00Z');return Number.isFinite(x)&&Number.isFinite(y)?Math.round((y-x)/86400000):null}
function directPrice(r){const u=num(r?.promotedUnits),rev=num(r?.promotedRevenue);return u>0&&rev>0?rev/u:null}

function buildSafeOrderSeries(rows,opt={}){
  const maxGap=Math.max(1,Math.round(num(opt.maxPriceGapDays,3))),stableTol=finite(opt.priceStableTolerance)?Math.abs(Number(opt.priceStableTolerance)):.02,resTol=finite(opt.orderResidualTolerance)?Math.abs(Number(opt.orderResidualTolerance)):.02;
  const a=(rows||[]).slice().sort((x,y)=>String(x.date).localeCompare(String(y.date))).map(r=>({...r,safeOrderUnits:null,safeOrderReliable:false,safeOrderPrice:null,safeOrderSource:'unavailable'}));
  const points=[]; for(let i=0;i<a.length;i++){const p=directPrice(a[i]);if(p>0)points.push({i,date:a[i].date,p})}
  for(let i=0;i<a.length;i++){
    const r=a[i]; if(num(r.totalRevenue)<=0){r.safeOrderUnits=0;r.safeOrderReliable=true;r.safeOrderSource='zero-revenue';continue}
    const p0=directPrice(r); let p=null,source=null;
    if(p0>0){p=p0;source='direct-promoted-price'}
    else{
      let lo=null,hi=null; for(const z of points){if(z.i<i)lo=z;else if(z.i>i){hi=z;break}}
      if(lo&&hi&&daysBetween(lo.date,r.date)<=maxGap&&daysBetween(r.date,hi.date)<=maxGap){const rel=Math.abs(hi.p-lo.p)/((hi.p+lo.p)/2);if(rel<=stableTol){p=(lo.p+hi.p)/2;source='stable-sandwich-price'}}
    }
    if(!(p>0))continue;
    const q=Math.max(1,Math.round(num(r.totalRevenue)/p)),res=Math.abs(q*p-num(r.totalRevenue))/Math.max(num(r.totalRevenue),1);
    if(res<=resTol){r.safeOrderUnits=q;r.safeOrderReliable=true;r.safeOrderPrice=p;r.safeOrderSource=source;r.safeOrderResidual=res}
  }
  return a;
}

function solve(A,b){const n=b.length,m=A.map((r,i)=>r.slice().concat(b[i]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(m[r][c])>Math.abs(m[p][c]))p=r;if(Math.abs(m[p][c])<1e-10)return null;[m[c],m[p]]=[m[p],m[c]];const d=m[c][c];for(let j=c;j<=n;j++)m[c][j]/=d;for(let r=0;r<n;r++){if(r===c)continue;const f=m[r][c];for(let j=c;j<=n;j++)m[r][j]-=f*m[c][j]} }return m.map(r=>r[n])}
function wls(X,y,w,ridge=1e-7){const k=X[0]?.length||0;if(!k||X.length<k)return null;const A=Array.from({length:k},()=>Array(k).fill(0)),b=Array(k).fill(0);for(let r=0;r<X.length;r++){const wr=Math.max(0,num(w[r],1));for(let i=0;i<k;i++){b[i]+=wr*X[r][i]*y[r];for(let j=0;j<k;j++)A[i][j]+=wr*X[r][i]*X[r][j]}}for(let i=1;i<k;i++)A[i][i]+=ridge;return solve(A,b)}
function weightedCorr(a,b,w){let sw=0,ma=0,mb=0;for(let i=0;i<a.length;i++){const q=Math.max(0,num(w[i],1));sw+=q;ma+=q*a[i];mb+=q*b[i]}if(!sw)return null;ma/=sw;mb/=sw;let c=0,va=0,vb=0;for(let i=0;i<a.length;i++){const q=Math.max(0,num(w[i],1)),da=a[i]-ma,db=b[i]-mb;c+=q*da*db;va+=q*da*da;vb+=q*db*db}return va>1e-12&&vb>1e-12?c/Math.sqrt(va*vb):null}
function weightedR2(y,p,w){let sw=0,my=0;for(let i=0;i<y.length;i++){const q=Math.max(0,num(w[i],1));sw+=q;my+=q*y[i]}if(!sw)return null;my/=sw;let sse=0,sst=0;for(let i=0;i<y.length;i++){const q=Math.max(0,num(w[i],1));sse+=q*(y[i]-p[i])**2;sst+=q*(y[i]-my)**2}return sst>1e-12?1-sse/sst:null}
function ppmlFit(X,y,baseW){const n=y.length,k=X[0]?.length||0;if(n<Math.max(k+4,12))return null;let beta=Array(k).fill(0);beta[0]=Math.log(Math.max(mean(y)||0,.1));for(let it=0;it<80;it++){const eta=X.map(x=>clamp(x.reduce((s,v,j)=>s+v*beta[j],0),-12,12)),mu=eta.map(Math.exp),z=eta.map((e,i)=>e+(y[i]-mu[i])/Math.max(mu[i],1e-6)),w=mu.map((m,i)=>Math.max(1e-8,m*num(baseW[i],1))),next=wls(X,z,w,1e-6);if(!next)return null;const d=Math.max(...next.map((v,j)=>Math.abs(v-beta[j])));beta=next;if(d<1e-7)break}
  const eta=X.map(x=>clamp(x.reduce((s,v,j)=>s+v*beta[j],0),-12,12)),mu=eta.map(Math.exp);return{beta,mu,n,k};}
function dowFeatures(iso){const d=new Date(iso+'T00:00:00Z').getUTCDay(),a=2*Math.PI*d/7;return[Math.sin(a),Math.cos(a)]}
function buildModelRows(days,opt={}){
  const safe=buildSafeOrderSeries(days,opt),byDate=new Map(safe.map(r=>[r.date,r])),lag=Math.max(0,Math.round(num(opt.orderLagDays,0))),active=safe.filter(r=>E.actualCpc(r)>0&&num(r.spend)>0),current=finite(opt.currentCpc)?Number(opt.currentCpc):median(active.slice(-3).map(E.actualCpc)),maxDate=active.at(-1)?.date,minDate=active[0]?.date,totalSpan=Math.max(1,daysBetween(minDate,maxDate)||1),bw=Math.log(1+num(opt.localCpcBand,.35)),halfLife=Math.max(7,num(opt.recencyHalfLifeDays,35)),proxy=opt.demandProxyByDate||null,priceByDate=opt.priceByDate||null,priceStable=!!opt.priceStable,stablePrice=finite(opt.stablePrice)?Number(opt.stablePrice):null;
  const rows=[];for(const r of active){const yd=new Date(r.date+'T00:00:00Z');yd.setUTCDate(yd.getUTCDate()+lag);const yrow=byDate.get(yd.toISOString().slice(0,10));if(!yrow?.safeOrderReliable||!Number.isFinite(yrow.safeOrderUnits))continue;const c=E.actualCpc(r),age=Math.max(0,daysBetween(r.date,maxDate)||0),rec=Math.exp(-Math.log(2)*age/halfLife),z=current>0?Math.log(c/current)/Math.max(bw,.05):0,local=Math.exp(-.5*z*z),trend=((daysBetween(minDate,r.date)||0)/totalSpan)-.5,[sn,cs]=dowFeatures(r.date),dp=proxy&&Number.isFinite(proxy[r.date])?Number(proxy[r.date]):null,pr=priceByDate&&Number.isFinite(priceByDate[r.date])?Number(priceByDate[r.date]):(priceStable&&stablePrice>0?stablePrice:null);rows.push({r,y:yrow.safeOrderUnits,logCpc:Math.log(c),logSpend:Math.log(num(r.spend)+1),logPrice:pr>0?Math.log(pr):null,trend,sinDow:sn,cosDow:cs,demandProxy:dp,weight:rec*local,cpc:c})}
  return{safe,rows,currentCpc:current,lagDays:lag,priceStable};
}
function fitLocalPpmlElasticity(days,opt={}){
  const b=buildModelRows(days,opt);let r=b.rows;if(r.length<18)return{betaCpc:null,pValue:1,n:r.length,safeOrderCoverage:days?.length?r.length/days.length:0,localCpcSpan:0,currentCpc:b.currentCpc,method:'PPML-local'};
  const proxyAvailable=r.filter(z=>Number.isFinite(z.demandProxy)).length>=Math.max(12,Math.floor(r.length*.7));
  const priceCoverage=r.length?r.filter(z=>Number.isFinite(z.logPrice)).length/r.length:0,usePriceControl=!b.priceStable&&priceCoverage>=.70;if(!b.priceStable&&usePriceControl)r=r.filter(z=>Number.isFinite(z.logPrice));
  const fields=['logCpc','logSpend',...(usePriceControl?['logPrice']:[]),'trend','sinDow','cosDow'],X=r.map(z=>[1,...fields.map(f=>z[f])]),y=r.map(z=>z.y),w=r.map(z=>z.weight),fit=ppmlFit(X,y,w);if(!fit)return{betaCpc:null,pValue:1,n:r.length,safeOrderCoverage:r.length/(days?.length||r.length),localCpcSpan:0,currentCpc:b.currentCpc,method:'PPML-local',priceControlUsed:usePriceControl,priceCoverage};
  const betaCpc=fit.beta[1],cpcs=r.map(z=>z.cpc),span=Math.max(...cpcs)/Math.min(...cpcs)-1;
  // Circular-shift randomization of CPC residuals conditional on pre-specified controls.
  // The internal peer-demand proxy is diagnostic only: in a shared-budget campaign it may itself be post-treatment.
  const controlFields=fields.filter(f=>f!=='logCpc'),C=r.map(z=>[1,...controlFields.map(f=>z[f])]),logc=r.map(z=>z.logCpc),cb=wls(C,logc,w,1e-7),demandCorr=proxyAvailable?weightedCorr(logc,r.map(z=>z.demandProxy),w):null;let demandVif=null;if(proxyAvailable){const D=r.map(z=>[1,z.logSpend,z.trend,z.sinDow,z.cosDow,z.demandProxy]),db=wls(D,logc,w,1e-7);if(db){const cp=D.map(x=>x.reduce((s,v,j)=>s+v*db[j],0)),r2=weightedR2(logc,cp,w);demandVif=Number.isFinite(r2)&&r2<.999?1/(1-r2):Infinity}}const demandConfounded=proxyAvailable&&((Number.isFinite(demandCorr)&&Math.abs(demandCorr)>=.80)||(Number.isFinite(demandVif)&&demandVif>=5));let pValue=1,valid=0,extreme=0;
  if(cb&&r.length>=20){const pred=C.map(x=>x.reduce((s,v,j)=>s+v*cb[j],0)),res=logc.map((v,i)=>v-pred[i]);for(let sh=1;sh<r.length;sh++){const Xs=r.map((z,i)=>[1,pred[i]+res[(i+sh)%r.length],...controlFields.map(f=>z[f])]),f=ppmlFit(Xs,y,w);if(!f)continue;valid++;if(Math.abs(f.beta[1])>=Math.abs(betaCpc)-1e-12)extreme++}pValue=valid?(extreme+1)/(valid+1):1}
  const effW=w.reduce((s,x)=>s+x,0)/(Math.max(...w)||1);return{betaCpc,pValue,n:r.length,effectiveN:effW,safeOrderCoverage:r.length/(days?.length||r.length),localCpcSpan:span,currentCpc:b.currentCpc,method:'PPML-local',fit,modelRows:r,lagDays:b.lagDays,useDemandProxy:false,demandProxyAvailable:proxyAvailable,demandCorrelation:demandCorr,demandVif,demandConfounded,priceControlUsed:usePriceControl,priceCoverage,priceStable:b.priceStable};
}
function benjaminiHochberg(ps){const m=ps.length,idx=ps.map((p,i)=>({p:Number.isFinite(Number(p))?clamp(Number(p),0,1):1,i})).sort((a,b)=>a.p-b.p),q=Array(m).fill(1);let prev=1;for(let j=m-1;j>=0;j--){const v=Math.min(prev,idx[j].p*m/(j+1));prev=v;q[idx[j].i]=clamp(v,0,1)}return q}
function computeExpansionEconomics(days,minChange=.05){const a=(days||[]).slice().sort((x,y)=>String(x.date).localeCompare(String(y.date)));let ds=0,dq=0,dr=0,n=0,success=0;for(let i=1;i<a.length;i++){const x=a[i-1],y=a[i];if(daysBetween(x.date,y.date)!==1||!x.safeOrderReliable||!y.safeOrderReliable)continue;const c1=E.actualCpc(x),c2=E.actualCpc(y);if(!(c1>0&&c2>0))continue;const dc=(c2-c1)/((c1+c2)/2);const spend=y.spend-x.spend;if(dc<minChange||spend<=0)continue;n++;ds+=spend;const od=y.safeOrderUnits-x.safeOrderUnits;dq+=od;dr+=num(y.totalRevenue)-num(x.totalRevenue);if(od>0)success++}
  return{expansions:n,deltaSpend:ds,deltaOrders:dq,deltaRevenue:dr,incrementalCpo:n&&dq>0?ds/dq:n?Infinity:null,marginalRoas:n&&ds>0?dr/ds:null,successRate:n?success/n:null};}
function classifyPriceAssociation(x){const b=Number(x.betaPrice),p=num(x.pricePValue,1);if(Number.isFinite(b)&&b>.15&&p<=.15)return{code:'PRICE_ENDOGENEITY_SUSPECTED',label:'Цена смешана со спросом',reason:`Положительная связь цены с заказами (β=${b.toFixed(2)}, p=${p.toFixed(3)}) похожа на эндогенность спроса, а не на обычную кривую спроса.`};if(Number.isFinite(b)&&b<-.25&&p<=.15)return{code:'PRICE_ASSOCIATION_DETECTED',label:'Есть отрицательная связь цены',reason:'Наблюдается ожидаемая отрицательная связь цены и заказов; это контроль confounder, не причинная рекомендация цены.'};return{code:'PRICE_CONTROL_AVAILABLE',label:'Цена учтена как контроль',reason:'Цена используется только для очистки CPC-сигнала.'}}
function priceBlocks(x){const c=x?.price?.priceStatus?.code;return['PRICE_CONFOUNDED','PRICE_DATA_INSUFFICIENT','PRICE_LOW_POWER','PRICE_ENDOGENEITY_SUSPECTED'].includes(c)}
function classifyTrustedRecommendation(x,s={}){const d=x.decisionModel||{},c=num(x.currentCpc),make=(code,label,step,reason,evidence='Низкая')=>({code,label,stepPct:step,targetCpc:c>0?c*(1+step):null,reason,evidence});
  if(!Number.isFinite(d.betaCpc)||d.n<20||d.effectiveN<10||d.safeOrderCoverage<.65||d.localCpcSpan<.12)return make('INSUFFICIENT','Нужен контролируемый CPC-тест',0,'Локальная PPML-модель недостаточно идентифицирована: не хватает надёжных заказов, локального диапазона CPC или эффективных наблюдений.');
  if(priceBlocks(x))return make('INSUFFICIENT','Сначала отделить цену от CPC',0,x.price?.priceStatus?.reason||'Цена недостаточно отделена от CPC.');
  if(!d.priceStable&&!d.priceControlUsed&&['PRICE_CONTROL_AVAILABLE','PRICE_ASSOCIATION_DETECTED'].includes(x.price?.priceStatus?.code))return make('INSUFFICIENT','Нужен чистый тест при фиксированной цене',0,'Цена менялась, но в локальной PPML недостаточно надёжных ценовых дней, чтобы отделить её эффект от CPC.');
  if(d.demandConfounded)return make('INSUFFICIENT','CPC смешан с общим спросом',0,`CPC слишком тесно связан с campaign-demand proxy (corr=${Number.isFinite(d.demandCorrelation)?d.demandCorrelation.toFixed(2):'—'}, VIF=${Number.isFinite(d.demandVif)?d.demandVif.toFixed(1):'—'}); отдельный CPC-эффект не идентифицируется.`);
  if(x.decisionLagConflict)return make('INSUFFICIENT','Эффект чувствителен к лагу',0,'Локальная PPML-оценка меняет направление на лаге 0–2 дня; исторический сигнал нельзя использовать для изменения CPC.');
  if(['LAG_SENSITIVE','TEMPORAL_SHIFT','CONFOUNDED','DATA_QUALITY'].includes(x.identifiability?.code))return make('INSUFFICIENT','Нужен чистый CPC-тест',0,x.identifiability.reason||'Исторический сигнал нестабилен.');
  const q=num(d.qValue,1),p=num(d.pValue,1),b=d.betaCpc,cart=Number(x.adjustedECart),econ=x.expansionEconomics||{},max=finite(s.maxIncrementalCpo)&&Number(s.maxIncrementalCpo)>0?Number(s.maxIncrementalCpo):null;
  if(b>.25&&q<=.10&&p<=.05&&( !Number.isFinite(cart)||cart>=0 )){if((max&&econ.incrementalCpo===Infinity)||(max&&Number.isFinite(econ.incrementalCpo)&&econ.incrementalCpo>max)||(Number.isFinite(econ.successRate)&&econ.expansions>=3&&econ.successRate<.5))return make('HOLD','Не повышать CPC',0,'Статистический сигнал есть, но наблюдаемая экономика расширений не подтверждает повышение.');return make('RAISE','Тест: повысить CPC',.05,`Наблюдательный локальный PPML-сигнал: E_CPC=${b.toFixed(2)}, p=${p.toFixed(3)}, q=${q.toFixed(3)}. Это не причинное доказательство — только контролируемый тест +5%.`,'Средняя')}
  if(b<-.25&&q<=.10&&p<=.05&&( !Number.isFinite(cart)||cart<=.15 ))return make('LOWER','Тест: снизить CPC',-.05,`Наблюдательный локальный PPML-сигнал: E_CPC=${b.toFixed(2)}, p=${p.toFixed(3)}, q=${q.toFixed(3)}. Это не причинное доказательство — только контролируемый тест −5%.`,'Средняя');
  return make('HOLD','Не менять',0,`Локальный CPC-сигнал недостаточно устойчив после FDR: E=${Number.isFinite(b)?b.toFixed(2):'—'}, p=${p.toFixed(3)}, q=${q.toFixed(3)}.`,'Низкая');}

function patchPriceStatus(x){if(!x?.price)return x;const p=x.price,status=classifyPriceAssociation({betaPrice:p.priceElasticityOrder,pricePValue:p.pricePValue,priceCoverage:p.priceCoverage,directPriceDays:p.directPriceDays,priceSpan:p.priceSpan,cpcPriceCorrelation:p.cpcPriceCorrelation,cpcVif:p.cpcVif,priceVif:p.priceVif,totalPricedOrders:p.totalPricedOrders,medianPairOrders:p.medianPairOrders,jointN:p.jointPairs});if(['PRICE_ADJUSTED','PRICE_EFFECT_MEASURED'].includes(p.priceStatus?.code))p.priceStatus=status;return x}
function ensureExperiment(x,rec=null){const e={...(x.experiment||{})},conds=[...(e.conditions||[])];for(const c of ['Не менять цену товара во время CPC-теста','Не менять бюджет/лимит кампании во время теста','Оценивать тест блоком полных дней, а не отдельным днём'])if(!conds.includes(c))conds.push(c);const active=num(x.currentCpc)>0&&num(x.regimeKnowledge?.clicks)>=20,blocked=rec?.code==='INSUFFICIENT'&&x.identifiability?.code!=='INACTIVE_CURRENT';if(blocked&&active){const below=num(x.history?.belowCount),above=num(x.history?.aboveCount),step=below>above+2?.05:-.10,recent=(x.days||[]).slice(-14),a=E.aggregateRegime(recent),need=(t,r)=>r>0?Math.ceil(t/r):99;e.needed=true;if(!(e.targetCpc>0)){e.stepPct=step;e.direction=step>0?'RAISE':'LOWER';e.targetCpc=num(x.currentCpc)*(1+step)}let days=Math.max(5,need(150,a.clicksPerDay||0),need(20,a.cartsPerDay||0),need(10,a.ordersPerDay||0));if(['LAG_SENSITIVE','TEMPORAL_SHIFT','CONFOUNDED','PRICE_CONFOUNDED','PRICE_DATA_INSUFFICIENT','PRICE_LOW_POWER'].includes(x.identifiability?.code)||x.decisionLagConflict)days=Math.max(days,7);e.days=Math.max(num(e.days,0),days);e.daysLabel=e.days>21?'>21':String(e.days);e.reason=rec.reason;e.volumeTargets=e.volumeTargets||{clicks:150,carts:20,orders:10};e.note='Это план набора идентифицирующих данных, а не гарантия причинного эффекта или statistical power.'}e.conditions=conds;return e}

E.analyzeCampaignRolling=function(rows,s={}){
  let out=baseAnalyze(rows,s).map(x=>patchPriceStatus(x));
  const byDate=new Map();for(const r of rows||[]){if(!byDate.has(r.date))byDate.set(r.date,[]);byDate.get(r.date).push(r)}
  out=out.map(x=>{const proxy={};for(const d of x.days||[]){const peers=(byDate.get(d.date)||[]).filter(r=>String(r.sku)!==String(x.sku));if(peers.length)proxy[d.date]=Math.log(1+peers.reduce((z,r)=>z+num(r.carts),0))}const safe=buildSafeOrderSeries(x.days||[],s),priceByDate={};for(const r of x.price?.priceSeries||[])if(Number.isFinite(r.historicalPrice))priceByDate[r.date]=r.historicalPrice;const priceStable=x.price?.priceStatus?.code==='PRICE_STABLE',opt={...s,currentCpc:x.currentCpc,demandProxyByDate:proxy,priceByDate,priceStable,stablePrice:x.price?.currentObservedPrice},decision=fitLocalPpmlElasticity(safe,opt),lag1=fitLocalPpmlElasticity(safe,{...opt,orderLagDays:1}),lag2=fitLocalPpmlElasticity(safe,{...opt,orderLagDays:2}),fits=[decision,lag1,lag2].filter(f=>Number.isFinite(f.betaCpc)&&f.pValue<=.15&&Math.abs(f.betaCpc)>=.25),lagConflict=fits.some((a,i)=>fits.slice(i+1).some(b=>Math.sign(a.betaCpc)!==Math.sign(b.betaCpc))),econ=computeExpansionEconomics(safe,num(s.minCpcChange,.05));return{...x,safeDays:safe,decisionModel:decision,decisionLagModels:[lag1,lag2],decisionLagConflict:lagConflict,expansionEconomics:econ,marginalCpo:econ.incrementalCpo,marginalRoas:econ.marginalRoas,experiment:ensureExperiment(x)}});
  const qs=benjaminiHochberg(out.map(x=>x.decisionModel?.pValue));out.forEach((x,i)=>x.decisionModel.qValue=qs[i]);
  out=out.map(x=>{const rec=classifyTrustedRecommendation(x,s),id={...(x.identifiability||{})};if(rec.code==='RAISE'||rec.code==='LOWER'){id.label='Наблюдательный сигнал — нужен тест';id.reason=rec.reason;id.needsExperiment=true}else if(rec.code==='INSUFFICIENT'){id.needsExperiment=true}const e=ensureExperiment(x,rec);if((rec.code==='RAISE'||rec.code==='LOWER')&&x.currentCpc>0){e.needed=true;e.targetCpc=rec.targetCpc;e.stepPct=rec.stepPct;e.direction=rec.stepPct>0?'RAISE':'LOWER';e.days=Math.max(num(e.days,0),5);e.daysLabel=String(e.days)}const d=x.decisionModel||{},priceOkay=!priceBlocks(x)&&(d.priceStable||d.priceControlUsed||!['PRICE_CONTROL_AVAILABLE','PRICE_ASSOCIATION_DETECTED'].includes(x.price?.priceStatus?.code)),reportable=Number.isFinite(d.betaCpc)&&d.n>=20&&d.effectiveN>=10&&d.safeOrderCoverage>=.65&&d.localCpcSpan>=.12&&!d.demandConfounded&&!x.decisionLagConflict&&priceOkay&&!['LAG_SENSITIVE','TEMPORAL_SHIFT','CONFOUNDED','DATA_QUALITY'].includes(x.identifiability?.code);d.reportable=reportable;d.reportReason=reportable?'Локальная PPML E пригодна как наблюдательный сигнал.':rec.reason;return{...x,adjustedEOrder:reportable?d.betaCpc:null,orderPValue:reportable?d.pValue:null,orderQValue:reportable?d.qValue:null,recommendation:rec,targetCpc:rec.targetCpc,identifiability:id,experiment:e}});
  lastDecisionAnalysis=out;return out;
};
E.getLastPriceAnalysis=()=>lastDecisionAnalysis;E.getLastDecisionAnalysis=()=>lastDecisionAnalysis;E.buildSafeOrderSeries=buildSafeOrderSeries;E.fitLocalPpmlElasticity=fitLocalPpmlElasticity;E.benjaminiHochberg=benjaminiHochberg;E.computeExpansionEconomics=computeExpansionEconomics;E.classifyTrustedRecommendation=classifyTrustedRecommendation;E.classifyPriceAssociation=classifyPriceAssociation;
return E;
});
