(function(){
'use strict';
const E=window.OzonElasticity;if(!E)return;
const rub=n=>Number.isFinite(n)?n.toLocaleString('ru-RU',{maximumFractionDigits:2})+' ₽':'—';
const ef=n=>Number.isFinite(n)?(n>0?'+':'')+n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const pf=n=>Number.isFinite(n)?n.toFixed(3):'—';
const last=()=>E.getLastPriceAnalysis?E.getLastPriceAnalysis():[];
const find=sku=>last().find(x=>String(x.sku)===String(sku));
function cls(c){return ['PRICE_STABLE','PRICE_ADJUSTED','PRICE_EFFECT_MEASURED'].includes(c)?'price-good':'price-warning'}
function enhanceRows(){for(const tr of document.querySelectorAll('#resultsBody tr[data-sku]')){const x=find(tr.dataset.sku),p=x?.price;if(!p)continue;const c=tr.children;if(c[1]&&!c[1].querySelector('[data-price-summary]')){const d=document.createElement('div');d.dataset.priceSummary='1';d.className='price-guard '+cls(p.priceStatus.code);d.textContent=`цена факт ${rub(p.minPrice)}–${rub(p.maxPrice)} · ${p.priceStatus.label}`;c[1].appendChild(d)}if(c[5]&&!c[5].querySelector('[data-price-e]')){const d=document.createElement('div');d.dataset.priceE='1';d.className='price-guard';d.innerHTML=`CPC|price ${ef(p.priceAdjustedEOrder)} · p=${pf(p.priceAdjustedPValue)}<br>E цены ${ef(p.priceElasticityOrder)} · p=${pf(p.pricePValue)}`;c[5].appendChild(d)}if(c[9]&&!c[9].querySelector('[data-price-status]')){const d=document.createElement('div');d.dataset.priceStatus='1';d.className='price-guard '+cls(p.priceStatus.code);d.textContent=p.priceStatus.label;c[9].appendChild(d)}}applyFilter()}
function ruIso(s){const m=/^(\d{2})\.(\d{2})\.(\d{4})$/.exec(String(s||'').trim());return m?`${m[3]}-${m[2]}-${m[1]}`:null}
function enhanceDetail(){const t=document.getElementById('detailTitle'),m=/SKU\s+(.+)/.exec(t?.textContent||'');if(!m)return;const x=find(m[1].trim()),p=x?.price,stats=document.getElementById('detailStats');if(!p)return;if(stats&&!stats.querySelector('[data-price-stat]')){const a=[['Цена факт.',rub(p.currentObservedPrice),`${rub(p.minPrice)}–${rub(p.maxPrice)} · ${p.priceStatus.label}`],['Покрытие цены',`${Math.round(p.priceCoverage*100)}%`,`${p.directPriceDays} прямых дней`],['E цены → заказы',ef(p.priceElasticityOrder),`p=${pf(p.pricePValue)} · диагностический сигнал`],['E CPC | цена',ef(p.priceAdjustedEOrder),`p=${pf(p.priceAdjustedPValue)} · Spend+Price adjusted`],['CPC × цена',Number.isFinite(p.cpcPriceCorrelation)?p.cpcPriceCorrelation.toFixed(2):'—',`VIF CPC ${Number.isFinite(p.cpcVif)?p.cpcVif.toFixed(1):'—'} · Price ${Number.isFinite(p.priceVif)?p.priceVif.toFixed(1):'—'}`]];for(const [n,v,s] of a){const d=document.createElement('div');d.className='stat-box';d.dataset.priceStat='1';d.innerHTML=`<span>${n}</span><strong>${v}</strong><small class="metric-sub">${s}</small>`;stats.appendChild(d)}}const head=document.querySelector('.daily-wrap thead tr');if(head&&!head.querySelector('[data-price-col]')){const th=document.createElement('th');th.dataset.priceCol='1';th.textContent='Цена факт.*';head.appendChild(th)}const map=new Map(p.priceSeries.map(r=>[r.date,r]));for(const tr of document.querySelectorAll('#dailyBody tr')){if(tr.querySelector('[data-price-col]'))continue;const r=map.get(ruIso(tr.children[0]?.textContent)),td=document.createElement('td');td.dataset.priceCol='1';td.innerHTML=Number.isFinite(r?.historicalPrice)?`${rub(r.historicalPrice)}<div class="metric-sub">${r.priceSource==='promoted-realized'?'прямая':'интерполяция'}</div>`:'—';tr.appendChild(td)}}
function ensureFilter(){if(document.getElementById('priceFilter'))return;const anchor=document.getElementById('measurementFilter');if(!anchor)return;const l=document.createElement('label');l.className='compact';l.innerHTML='<span>Цена</span><select id="priceFilter"><option value="ALL">Все</option><option value="PRICE_STABLE">Стабильна</option><option value="PRICE_ADJUSTED">Скорректирована</option><option value="PRICE_EFFECT_MEASURED">Есть ценовой сигнал</option><option value="PRICE_CONFOUNDED">CPC × цена</option><option value="PRICE_LOW_POWER">Мало заказов</option><option value="PRICE_DATA_INSUFFICIENT">Данных цены мало</option></select>';anchor.parentElement?.insertAdjacentElement('afterend',l);l.querySelector('select').addEventListener('change',applyFilter)}
function applyFilter(){const v=document.getElementById('priceFilter')?.value||'ALL';for(const tr of document.querySelectorAll('#resultsBody tr[data-sku]'))tr.style.display=v==='ALL'||find(tr.dataset.sku)?.price?.priceStatus?.code===v?'':'none'}
function enhance(){ensureFilter();enhanceRows();enhanceDetail()}
const st=document.createElement('style');st.textContent='.price-guard{font-size:10px;color:var(--muted);margin-top:3px;line-height:1.25}.price-warning{color:var(--warn);font-weight:700}.price-good{color:var(--raise);font-weight:700}';document.head.appendChild(st);
const grid=document.querySelector('.method-grid');if(grid&&!grid.querySelector('[data-price-method]')){const d=document.createElement('div');d.dataset.priceMethod='1';d.innerHTML='<h3>Поправка на цену</h3><p>Историческая цена берётся только из Продажи в продвижении / Продано товаров. «Цена товара» не считается историческим рядом. Совместная модель: Δlog(orders+1) ~ Δlog(CPC) + Δlog(spend+1) + Δlog(price). Слой цены может подтвердить или заблокировать CPC-действие, но не создаёт новое.</p>';grid.appendChild(d)}
const mo=new MutationObserver(()=>setTimeout(enhance,0));mo.observe(document.body,{subtree:true,childList:true});setTimeout(enhance,0);
})();